spring:
  application:
    name: OfficeAPI
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}