spring:
  application:
    name: OfficeAPI
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_office
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

#Create your own pair of keys in ('/src/main/resources') using OpenSSL in the terminal!
jwt:
  #openssl genpkey -algorithm RSA -out private_key.pem -pkeyopt rsa_keygen_bits:2048
  private:
    key: classpath:private_key.pem
  #openssl rsa -pubout -in private_key.pem -out public_key.pem
  public:
    key: classpath:public_key.pem